// <auto-generated />
using LLB.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LLB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324103000_AddPostFormationReferenceNumbers")]
    partial class AddPostFormationReferenceNumbers
    {
    }
}
